### ISSUE TITLE
Remove "error" field from errors.

### ISSUE THREAD

**Issue by cyantarek** [grpc-ecosystem/grpc-gateway#1098]
```go
body := &errorBody{
		Error:   s.Message(),
		Message: s.Message(),
		Code:    int32(s.Code()),
		Details: s.Proto().GetDetails(),
}
```

Here ([link](https://github.com/grpc-ecosystem/grpc-gateway/blob/3c06998610d4d2edea99d12228b1f6ea2d943ce4/runtime/errors.go#L109))

The Error and Message both field got s.Message(), I think it's not clean to duplicate the same thing. I don't know if there's any special intention behind it.

Please let us know. Thanks.

**Comment by johanbrandhorst** [comment]
Hi @cyantarek. The `message` field was added in https://github.com/grpc-ecosystem/grpc-gateway/pull/718 to make the error output of the gRPC-Gateway consistent with the Google RPC Status definitions JSON representation: https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto#L80. Unfortunately, because we already had `error` defined in our responses, we couldn't remove it without breaking backwards compatibility. So we've had to keep both. We hope to be able to remove the `error` field in a future 2.0 release (though there is currently no roadmap for when such a release might happen).

Hope that explains it!

**Comment by johanbrandhorst** [comment]
We want to fix this for v2

**Comment by srenatus** [comment]
Since it's a breaking change anyways, are we to just remove the field in [`internal/errors.proto`](https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/internal/errors.proto#L9), renumbering the others?

**Comment by johanbrandhorst** [comment]
Sure thing

**Comment by johanbrandhorst** [comment]
Actually, not sure we even need errors.proto anymore. We probably will just marshal the `status.Status` directly.

**Comment by srenatus** [comment]
I've started looking into this. I'll include the status change. :)

**Comment by johanbrandhorst** [comment]
This is done in `v2`.
