### ISSUE TITLE
Feature request: Access to more information about JSON parsing errors

### ISSUE THREAD

**Issue by torkelrogstad** [grpc-ecosystem/grpc-gateway#1123]
Consider this snippet: 

```proto
service Foo {
  rpc Bar(Baz) returns(Baz) {
    option (google.api.http) = {
      post : "/some/path"
      body : "*"
    };
  }
}

message Baz {
  Nested nested = 1;
}

message Nested {
  int32 field = 1;
} 
```

Now, if you send a request `POST /some/path { "field": "string" }`, we end up with a error that says `json: cannot unmarshal string into Go value of type map[string]json.RawMessage`. It's not possible to see the name of the field that failed parsing. This is also the case for other parsing failure, for example converting between date times, numbers and strings. It would be really nice to have access to: 

* The name of the field that failed parsing
* The value we tried to parse
* The type we tried to parse it to

Perhaps this could be added to the error in the `Details` field?

**Comment by achew22** [comment]
@torkelrogstad, sorry about that. We definitely know that the default marshaller for `jsonpb` leaves a lot to be desired. We import that from the go implementation of protobuf. This means the code isn't in this repo, but instead is in another castle (frowning toad emoji).

On the plus side, the issue is [being tracked](https://github.com/golang/protobuf/issues/266) by the protobuf team. On the minus side, they are only going to fix it with v2. On the other plus side there does always exist an alternate that claims to have better error reporting. I try really hard not to endorse any projects that I haven't used, and I haven't used this one, so I'm not going to include a direct link to it, but it is referred to in that bug. I believe you can use the interface we already provide to replace the Marshaller and that should get you there.

Please report back with how things went. If you want to be especially helpful a PR into the documentation would be extra nice!

PS: for future bugs it is generally kind to the contributers to fill out the bug template with all the information requested.

**Comment by torkelrogstad** [comment]
Thanks for clarifying how this works. I took a stab at making the unmarshaler configurable: https://github.com/torkelrogstad/grpc-gateway/commit/7e55a52bed32fa691f9b020b91453d8401948050. The downside of that approach would be that setting the unmarshaler would be package-level operation. That could be avoided though, with a different implementation. I did it this way as a proof of concept.

With this (and using the project linked to in the issue you mentioned) , I end up with a nicer error message: `unparsable field Permissions: json: cannot unmarshal string into Go value of type ...`. However, it is still a string, because the error returned after doing decoding gets inserted into a regular gRPC status: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/gengateway/template.go#L488

One solution here could be to not use `status.Errorf`, but instead implement a custom error that wraps a `status.Status` as well as whatever error was returned from the decoding operation. How would you feel about a solution like that?

**Comment by johanbrandhorst** [comment]
Thanks for the POC, what would be better than wrapping the status is to make use of the optional "details" perhaps? Feel free to submit a PR that allows the unmarshaler to me configured.

**Comment by torkelrogstad** [comment]
I'll take a look at that. Before I delve too deep into the rabbit hole: should I define a new message in a `.proto` file and compile that to Go, or is there something standardized I could use?

**Comment by johanbrandhorst** [comment]
The error details is an array of type `any.Any`, so you can put anything you like in there, though it is considered best practice (AFAIK) to use one of the types from the `errdetails` proto ([proto file](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto), [generated go package](https://github.com/google/go-genproto/tree/master/googleapis/rpc/errdetails/error_details.pb.go). See https://jbrandhorst.com/post/grpc-errors/ (:wink:) for more information.
