### ISSUE TITLE
Enum string values not supported by grpc gateway

### ISSUE THREAD

**Issue by archanabs19** [grpc-ecosystem/grpc-gateway#1159]
Request:
![image](https://user-images.githubusercontent.com/61829554/75977285-1085d100-5f02-11ea-8e56-7197d949d145.png)
Response is "unknown value \"DIFF\" for enum mode"
 gRPC Gateway is accepting only int values but protoc-gen-swagger is sending string values. Ideally, gRPC Gateway will accept both string and int values of an enum.

**Comment by johanbrandhorst** [comment]
This happens if you configured your JSON marshaler to parse enums as ints. By default it should parse strings. See https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/marshaler_registry.go#L16. You can use a custom marshaller to support both strings and enums.

Please join the grpc-gateway support channel on Gophers slack for this sort of debugging.

**Comment by archanabs19** [comment]
EnumsAsInts value is not set. So, by default, its taking string itself. Still, its unable to parse.

**Comment by johanbrandhorst** [comment]
Sorry to be brusque but I think this is a misconfiguration issue. Maybe you could join the support channel (#grpc-gateway) on Gophers slack (https://invite.slack.golangbridge.org/) and I can help you there.
