### ISSUE TITLE
grpc-gateway equivalent in the grpc python package

### ISSUE THREAD

**Issue by Talador12** [grpc-ecosystem/grpc-gateway#1613]
## 🚀 Feature

To allow for more use of the `grpc-gateway`, it should be available in the [grpc python package](https://pypi.org/project/grpc/)

I have found a [python example](https://gist.github.com/doubleyou/41f0828e4b9b50a38f7db815feed0a6c) that claims to integrate this kind of gateway via python. Is this the accepted method?

I am going to crosspost this to the `grpc` python package repo

### Additional context
Crossposted with the [grpc/grpc repo](https://github.com/grpc/grpc/issues/23979)

**Comment by achew22** [comment]
This sounds like a packaging decision for the [grpc/grpc team](https://github.com/grpc/grpc/issues/23979), as you mentioned. I'm going to close this issue since there is no action that we can take here but I am watching along on the linked issue and will track progress.

Good luck getting grpc-gateway included!

**Comment by Talador12** [comment]
gRFC proposal - https://github.com/grpc/proposal/pull/208

grpc google group discussion - https://groups.google.com/g/grpc-io/c/rEfqlLL9Emw
