### ISSUE TITLE
Merge swagger definitions generated by swaggo/swag init and protoc --swagger_out command

### ISSUE THREAD

**Issue by duclm2609** [grpc-ecosystem/grpc-gateway#1651]
Hi all,
Currently my service served both RESTful API and gRPC (via grpc-gateway) under a web server. For native REST endpoint, I generate swagger by command `swag init`. For REST endpoint proxied for gRPC function, I generate it by using `protoc `command with option `--swagger_out`. How do I merge theses 2 output file into single swagger definition file automatically? Thank you.

**Comment by achew22** [comment]
Unfortunately we don't have any utilities for modifying, merging or otherwise editing swagger definitions. All we do is generate the swagger associated with your protos. There are a large number of external projects that can be used to merge your swagger definitions. I would recommend trying then out.

If you do have any issues around the generated swagger definitions, please come back and I would love to help. You can either reopen this issue or make a new one. I hope you can understand that since this is a volunteer effort and we try to respond to all bugs, sometimes we can't help other than to point you in a general direction. Thanks so much!
