### ISSUE TITLE
 undefined: runtime.ServerTransportStream

### ISSUE THREAD

**Issue by archanabs19** [grpc-ecosystem/grpc-gateway#1664]
## 🐛 Bug Report

The handlers generated have en error in the pb.gw.go files. 

`example.pb.gw.go:189:14: undefined: runtime.ServerTransportStream`

I see in the grpc-gateway commit history that changes have been made related to this. 

![image](https://user-images.githubusercontent.com/61829554/93059087-dc981f00-f68d-11ea-8e6d-64ade813de4e.png)

Is there anything I need to change at my end?

## Your Environment

grpc-gateway version: 1.14.3

**Comment by johanbrandhorst** [comment]
Hi, this is happening because you're using a dfferent version of the generator and the runtime. Try upgrading your gateway to 1.14.8 and it should go away. See our [installation instructions](https://github.com/grpc-ecosystem/grpc-gateway#installation) for more information on how to avoid this type of error.
