### ISSUE TITLE
Allow client to disable sending of trailers by omitting "TE" header.

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc-ecosystem/grpc-gateway#1709]
## 🐛 Bug Report

We shouldn't send trailers unless the client sends the "TE" trailer.

See https://github.com/grpc-ecosystem/grpc-gateway/issues/1697 for more context

**Comment by anthonydevelops** [comment]
@johanbrandhorst can I take on this issue?

**Comment by johanbrandhorst** [comment]
Absolutely! Please do.

**Comment by anthonydevelops** [comment]
@johanbrandhorst Seems someone has begun working on this already with a draft PR, so I'll go ahead and un-assign myself for now. Thanks for the opportunity though! I'll try tackling the next one I feel confident enough to do. 👍

**Comment by johanbrandhorst** [comment]
I think #1709 is actually trying to solve #1697, so this one is still up for grabs!

**Comment by johanbrandhorst** [comment]
I think #1709 is actually trying to solve #1697, so this one is still up for grabs!

**Comment by bytecook** [comment]
@johanbrandhorst ,
My solution allows the caller of the API to embed an outgoingTrailerMatcher of `type TrailerMatcherFunc func(string) (string, bool)` passed in upon ServeMux construction  in order to customize Forward Response behavior, so that gRPC trailers will not be exposed to an http client even if "TE" is not omitted. 

The functionality of omitting "TE" to not send trailers is already in the code base. See runtime/errors.go lines 156-180:
`	// RFC 7230 https://tools.ietf.org/html/rfc7230#section-4.1.2
	// Unless the request includes a TE header field indicating "trailers"
	// is acceptable, as described in Section 4.3, a server SHOULD NOT
	// generate trailer fields that it believes are necessary for the user
	// agent to receive.
	var wantsTrailers bool

	if te := r.Header.Get("TE"); strings.Contains(strings.ToLower(te), "trailers") {
		wantsTrailers = true
		handleForwardResponseTrailerHeader(w, md)
		w.Header().Set("Transfer-Encoding", "chunked")
	}

	st := HTTPStatusFromCode(s.Code())
	w.WriteHeader(st)
	if _, err := w.Write(buf); err != nil {
		grpclog.Infof("Failed to write response: %v", err)
	}

	if wantsTrailers {
		handleForwardResponseTrailer(w, md)
	}`

Still working on #1697, #1709 and it's testing. Still unsure of how to test in handler_test.go, the only test headers I see are in mux_test.go.I feel like both test files need to be modified in order to test this functionality. The modified function, `func handleForwardResponseServerMetadata(w http.ResponseWriter, mux *ServeMux, md ServerMetadata)`

**Comment by johanbrandhorst** [comment]
The handling of the "TE" trailer is only present in the error handler, not the normal path (see https://github.com/grpc-ecosystem/grpc-gateway/blob/v2/runtime/handler.go#L166). I'm not sure what you're trying to say but you're not fixing this case in your PR.

**Comment by bytecook** [comment]
My mistake
