### ISSUE TITLE
protoc-gen-swagger: Implement Response Header(s) object, Implement Field Enum,Example&Format attributes

### ISSUE THREAD

**Issue by elijah-roberts** [grpc-ecosystem/grpc-gateway#1729]
## 🚀 Feature

My team would like to auto-generate swagger/openapi docs from our proto files, however there are certain features that are missing that we would need in order to move away from manually managed openapi docs:
* Headers/Header Object support - We currently return an header for all success, and failure responses and need to be able to define this via the `grpc.gateway.protoc_gen_swagger.options.openapiv2_operation` [Responses](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#responseObject) [Headers](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#headersObject) Object. 
![image](https://user-images.githubusercontent.com/19742213/95417353-19081500-08f2-11eb-81c2-90d6bdc9d34c.png)

* grpc.gateway.protoc_gen_swagger.options.openapiv2_field `example` attribute support (cleaner than `example_string`)

*  grpc.gateway.protoc_gen_swagger.options.openapiv2_field `format` attribute support
![image](https://user-images.githubusercontent.com/19742213/95417389-2c1ae500-08f2-11eb-92b0-519116f630a8.png)

*  grpc.gateway.protoc_gen_swagger.options.openapiv2_field `enum` attribute support
![image](https://user-images.githubusercontent.com/19742213/95417218-b4e55100-08f1-11eb-871f-c39abaa99716.png)

**Comment by johanbrandhorst** [comment]
Thanks for your interest, and I see you already took a stab at fixing this in #1730, however I had one small comment. The `example_string` is as it is because we couldn't remove the `example` field, I think we want to make any new `example` fields strings from the start. The `example` field in our `v2` branch is already a string.

Also, generally we've not been accepting new work on the `v1` version of the gateway at this point (the `master` branch), because we want to encourage users to move to `v2`, whose stable release is imminent. However, since you've already done all the work I think we can allow it in this case, though please be aware that we'll ask you to cherry-pick the changes across to v2 as well.

**Comment by elijah-roberts** [comment]
@johanbrandhorst The original goal of this issue was to enable auto-generation of required open api items via implementing missing annotation objects. 

I found another object that we need to implement for our use case, which is the parameters object, on the operations annotation. Currently only body parameters are implemented.

Do you want me to put this into a separate issue, and PR or include it with the existing one? I have the majority of the logic working locally, I am just implementing some more tests, and validation functions.

**Comment by johanbrandhorst** [comment]
If we could do it in a separate PR I would appreciate it, thank you.

**Comment by johanbrandhorst** [comment]
I think this is done?

**Comment by elijah-roberts** [comment]
Yes, it was merged to both v1 and v2

**Comment by johanbrandhorst** [comment]
Thanks!
