### ISSUE TITLE
protoc-gen-swagger: support a header parameter

### ISSUE THREAD

**Issue by hiroyoshii** [grpc-ecosystem/grpc-gateway#1737]
## 🚀 Feature
OpenAPI 2.0 support a header-parameter [[link](https://swagger.io/docs/specification/2-0/describing-parameters/#header-parameters)].

I wish to specify header parameter as follow:
```
message Test {
  string myheader =1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {in: HEADER}];
}
```
Should protoc-gen-swagger support a header parameter?

**Comment by johanbrandhorst** [comment]
I don't think that will be possible to represent according to the [http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) spec. It defines 3 different ways to specify data: in query parameters, in path parameters, or in the request body. Passing data in the header is not supported, as far as I know, so we're not going to support it in the grpc-gateway.

**Comment by electrofelix** [comment]
Just run into a case where this would have been useful, trying to avoid needing to use multiple API frameworks in the same service where it needs to accept calls from other services that have been defined using openapiv2. Unfortunately I have no control over the API itself, I'm stuck with implementing it to conform to the spec.

If there was some way to express this in the proto files it would make it cleaner than needing to add special handling to copy the header value across to the field at some point.

I suspect it would also make it easier to sell migrating services from REST to gRPC as well as it would allow expressing more of the openapiv2 spec directly via proto files. I do understand why google might not be interested in adding this to googleapis since they control all of the APIs they are using, they don't create this problem in the first place for themselves.

However if the long term goal is hopefully that everyone eventually migrates to gRPC, finding a way to support this would appear to help make it easier.

Btw, there doesn't appear to be any way to raise this in the googleapis repo as there are no issues and no discussions, so not clear where this could be raised besides this repo.
