### ISSUE TITLE
The "Use go templates" page is missing its actual go templates

### ISSUE THREAD

**Issue by cpick** [grpc-ecosystem/grpc-gateway#1773]
## 📚 Documentation

[usegotemplates.md](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/docs/_docs/usegotemplates.md) contains examples that have go templates (ie things surrounded in double-curly-brackets), but the website's [usegotemplates.html](https://grpc-ecosystem.github.io/grpc-gateway/docs/usegotemplates.html) has those important sections stripped out.

Perhaps the pipeline that produces the website itself uses go templates and is trying to interpret them?

**Comment by johanbrandhorst** [comment]
Haha, that's a great bug. Yeah we obviously use a mustache templating engine somewhere. I wonder if we can escape these in the docs? It's possible the run the docs site locally via the script in the `docs` folder, so if someone would an easy way to experiment locally, you can run:
```shell
$ JEKYLL_GITHUB_TOKEN=<your-github-token> ./run.sh
```
From the `./docs` directory.

**Comment by johanbrandhorst** [comment]
CC @Jeremytjuh

**Comment by iamrajiv** [comment]
@cpick @johanbrandhorst I think this happening because Jekyll uses liquid tags and double curlies are getting ripped out by the liquid processor. To overcome this issue we have to use `{% raw %}` tag something like this
```md
## {% raw %}{{.RequestType.Name}}{% endraw %}
```
This is not happening in `usegotemplates.md` only it might be happening to other docs since we can know which docs are facing this issue by running `bundle exec jekyll serve` so if it gives `Liquid Warning: Liquid syntax error` means there is a similar issue in that doc. I will update the files in the new doc website.

**Comment by johanbrandhorst** [comment]
This is fixed now: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizingopenapioutput/#using-go-templates-in-protofile-comments :tada:
