### ISSUE TITLE
Issue with converting to the bytes data type

### ISSUE THREAD

**Issue by holahula** [grpc-ecosystem/grpc-gateway#1781]
## 🐛 Bug Report
There is an issue with using a Javascript byte array as the protobuf type `bytes`.
This is the code used to create the byte array
```
const b64 = uri.replace('data:image/jpeg;base64,', '');
const byteArray = Array.from(Uint8Array.from(window.atob(b64), c => c.charCodeAt(0)));
```

## To Reproduce

1. Create sample rpc function + POST annotation that takes a `bytes` input field in the request message. 
2. Post to the associated REST endpoint with some valid `Uint8Array `.
3. Notice error posted below

## Expected behavior
Request should succeed.

![image](https://user-images.githubusercontent.com/17057747/97527423-a71b6c80-1981-11eb-9f54-54619c7f61a5.png)
This rpc function succeeds when using a Go gRPC client + `[]byte` as the input field. Thus, I suspect the issue is somewhere before the request reaches the rpc function (in the area handled by grpc-gateway)

## Actual Behavior
![image](https://user-images.githubusercontent.com/17057747/97527046-c9f95100-1980-11eb-94da-ed199ec68732.png)

## Your Environment
OSX
Go 1.14.2
github.com/grpc-ecosystem/grpc-gateway/v2 v2.0.1

**Comment by mog3n** [comment]
I am having the same issue as well

**Comment by johanbrandhorst** [comment]
If you want to receive a `bytes` type, you have to use the JSON representation of `bytes`, which is a URL-safe base64 encoding of the bytes, as per the language specification: https://developers.google.com/protocol-buffers/docs/proto3#json.

**Comment by veith** [comment]
What is about `google.api.HttpBody` or something similar?

It would be **very nice** if there is a type which can receive raw binary data as body, and all according metadata via headers (`Content-Type video/mp4`). 

Browsers of today can send real binary data (`const binaryData = new Uint8Array(buffer);`).
Curl scripts also (`curl  --data-binary "@filepath"`). 

[This would reduce the transferred data size by 33%.](https://developer.mozilla.org/en-US/docs/Glossary/Base64#encoded_size_increase) 

I refer to HttpBody, because this type is only usable as a "root" response type in a transcoded context, why not bidirectional?

**Comment by johanbrandhorst** [comment]
Seems reasonable to add support for unmarshaling a HTTPBody as raw data. I expect you probably would just update the definition in https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/marshal_httpbodyproto.go. Could you create a separate issue though?
