### ISSUE TITLE
Can protoc-gen-swagger hide the specified fields?

### ISSUE THREAD

**Issue by yunqiang-sun** [grpc-ecosystem/grpc-gateway#1791]
## 🚀 Feature

I want to hide certain fields in the json generated by protoc-gen-swagger

**Comment by johanbrandhorst** [comment]
I don't think we support this today. If you'd like to contribute this I would consider it if you can come up with a good design.

**Comment by ewhauser** [comment]
I think extensions are the best way to handle hidden/private operations, parameters, fields, etc. There's an existing open source tool that allows you to filter your generated schema: https://github.com/Mermade/openapi-filter

I don't believe `protoc-gen-swagger` lets you define `extensions` on fields at the moment, but that could be added.

**Comment by santhosh-v** [comment]
Field level support is there, I think with this we could use this filter. Is it possible to add soon ?

**Comment by johanbrandhorst** [comment]
This isn't going to be added unless someone has the time to contribute it.

**Comment by james-o-johnstone** [comment]
Added a PR https://github.com/grpc-ecosystem/grpc-gateway/pull/2418 to define `extensions` on fields, so fields could be marked with an `x-internal` extension and filtered using https://github.com/Mermade/openapi-filter

**Comment by johanbrandhorst** [comment]
There is now an alternative implementation to hiding fields/RPCs in https://github.com/grpc-ecosystem/grpc-gateway/pull/2578. We probably only want to merge one, so would interested parties weigh in on which they would prefer?

**Comment by BCook98** [comment]
I'm slightly biased towards https://github.com/grpc-ecosystem/grpc-gateway/pull/2578 😉. 

Both are nice solutions towards hiding fields/RPCs, but `google.api.VisibilityRules` provides the ability to completely hide fields from the output. That way consumers never know a field exists, instead of having to rely on the Swagger renderer/ codegen to do that for you.

That being said it looks like https://github.com/grpc-ecosystem/grpc-gateway/pull/2418 is still useful in other scenarios where you want to apply other swagger extensions to fields and schemas.

**Comment by ewhauser** [comment]
I concur with @BCook98. First class support for `google.api.VisbilityRules` seems like the way to go - I'm not sure this was around (or at least I didn't know about it) when I suggested extensions.

I also agree that these two implementations are not mutually exclusive.

**Comment by johanbrandhorst** [comment]
Fair points, lets consider each on its own merits, thank you both!
