### ISSUE TITLE
Looking for a way to extract path parameters in middleware

### ISSUE THREAD

**Issue by Azuka** [grpc-ecosystem/grpc-gateway#1821]
## 📚 Documentation

I'm not sure if I'm looking in the right place, but I'd like to apply a middleware to extract path parameters and add to tracing. e.g.

`/users/{userId}`, is there a context param that returns a `map[string]string` (or other map) or a method that will reparse the request and return the same, so I can do something like:

```go
for k, v := range attrs {
    traceImpl.addAttribute(k, v)
}
```

**Comment by johanbrandhorst** [comment]
Does this middleware need to live on the grpc-gateway side? You can always implement this as a gRPC interceptor instead, which has access to the request and response values.

**Comment by Azuka** [comment]
@johanbrandhorst, it's more the convenience of instrumenting important parameters included in the path (and with an interceptor, I'd need to filter sensitive values).

**Comment by johanbrandhorst** [comment]
I don't think we support this at the moment. Certainly you could just do it manually with a `http.Handler` wrapping the `ServeMux`. Is that suitable?

**Comment by aranw** [comment]
Am trying to figure out a way to extract the gRPC Gateway Path Parameter in my HTTP Middlewares for logging/metrics/etc and found that right now it's not possible because the only way to add middleware is to wrap the gRPC Gateway Servemux

Would it be possible rather than wrapping the gRPC Gateway Servemux to instead wrap the internal handlers after the requests have been annotated?

**Comment by johanbrandhorst** [comment]
You can create a client side interceptor which happens before the network request. You should be able to use https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/v2/runtime?utm_source=godoc#HTTPPathPattern to get the pattern.
