### ISSUE TITLE
Unexpected response on /v2/example/errorwithdetails

### ISSUE THREAD

**Issue by isbang** [grpc-ecosystem/grpc-gateway#1842]
## 🐛 Bug Report

When I run the example `/v2/example/errorwithdetails`, I got an unexpected message below.

```json
{
  "code": 13,
  "message": "failed to marshal error message"
}
```

## To Reproduce

1. Setup Docker
```bash
docker run -it -p 8080:8080 golang:1.15 /bin/bash
```
2. Setup environment inside of docker
```bash
apt-get update && apt-get install npm -y && npm install -g gulp-cli
GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/v2
cd /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.1/examples/internal/browser
npm install && gulp bower && gulp backends
```
3. Test example outside of the docker
```bash
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/v2/example/errorwithdetails'
```

## Expected behavior

Response message below
```json
{
  "code": 2,
  "message": "with details",
  "details": [
    {
      "stackEntries": [
        "foo:1"
      ],
      "detail": "error debug details"
    }
  ]
}
```

https://github.com/grpc-ecosystem/grpc-gateway/blob/865774a90ce89b9df9ed9a58e79df76cc4f591b7/examples/internal/server/a_bit_of_everything.go#L310-L320

## Actual Behavior

Response message bellow with status code 500
```json
{
  "code": 13,
  "message": "failed to marshal error message"
}
```

## Your Environment

Mac os Catalina v10.15.7
Docker version 19.03.13, build 4484c46d9d
Image golang:1.15

**Comment by johanbrandhorst** [comment]
TIL we have a gulpfile in the depths of the examples :laughing:. Thanks for digging this up. I expect this is happening because the grpc-gateway server defined in https://github.com/grpc-ecosystem/grpc-gateway/tree/master/examples/internal/gateway doesn't have a way to understand the error details defined in the message returned from the gRPC server. It needs to import `google.golang.org/genproto/googleapis/rpc/errdetails` in order to be able to translate these messages from protobuf to JSON.

Would you like to contribute this fix and confirm it works?

**Comment by isbang** [comment]
I am not sure if I can fix this but I hope to try. May I try this?

In my opinion, `main.opts` from `grpc-gateway/examples/internal/cmd/example-gateway-server/main.go#L26` needs `Mux` contains `ErrorHandlerFunc` to translate `errdetails` message. How do you think?
