### ISSUE TITLE
"date"-format of timestamp values in OpenAPI spec and URL parameters

### ISSUE THREAD

**Issue by tanordheim** [grpc-ecosystem/grpc-gateway#1868]
## 🐛 Bug Report

Defining `format` on `google.protobuf.Timestamp` fields using annotations does not seem to be correctly captured during OpenAPI JSON generation. The generated gateway also seems to be unable to handle requests for these fields due to parsing issues.

## To Reproduce

Define a `google.protobuf.Timestamp` field with an explicit `format` in a model like this:

```proto
service Foo {
  rpc Bar(BarReq) returns (BarRes) {}
}

message BarReq {
  google.protobuf.Timestamp ts = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    format: "date"
  }];
}

message BarRes {}
```

1. The `format`-option for the field doesn't it into the Swagger spec generated (I use `protoc -I. --openapiv2_out=allow_merge=true,merge_file_name=api:./docs/openapi/ api1/*.proto api2/*.proto`), these fields still retain their default `"format": "date-time"` in the generated JSON.
2. The query parsing code is hardcoded to parse incoming data as `time.RFC3339Nano` in https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query.go#L251 - ignoring any custom formats on this, causing incoming request handling to fail for these messages as contains an invalid format.

I'd be happy to contribute a fix to this, and I believe it's at least somewhat related to #1683 but some pointers before I start would be helpful.

## Expected behavior

1. It should be possible to override the timestamp format for `google.protobuf.Timestamp` fields.
2. The timestamp format for a field should be honored when parsing URL arguments (path or query string) during deserialization.

## Actual Behavior

1. Timestamp format is always set to `date-time` regardless of any `format`-annotations in the proto file.
2. Parsing URL arguments fails if the value for a `google.protobuf.Timestamp` is not in a `time.RFC33339Nano` format.

## Your Environment

- MacOS Big Sur (11.0.1)
- Go 1.15.5
- grpc-gateway version 2.0.1

**Comment by johanbrandhorst** [comment]
Hi Trond, thanks for your bug report! There are several issues to discuss here:
* The OpenAPI annotations currently do not change the behaviour of the gateway parser. I think we want to keep it this way, as currently, the protoc-gen-grpc-gateway generator does not read (and does not need to read) the OpenAPI annotations. So I don't think we can make this automatic from just the annotation alone.
* The format for the well-known types not being overridable is probably a bug. I don't see a reason not to allow a user to override it, as long as they know it may break their parsing. So that is something we can fix. I would start by looking at the openapiv2 template.go: https://github.com/grpc-ecosystem/grpc-gateway/blob/b9e53fb4c49ae0409d11aca4e80e24b79726d2a9/protoc-gen-openapiv2/internal/genopenapi/template.go#L468. It should be possible to create a failing test and go from there. Note that we can only support this override in query parameters, not in the body since we can't control how `protojson` parses the body to this degree.
* We already support providing a custom query parameter parser function, see https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#SetQueryParameterParser. This, in combination with a fix to the above, should be all you need for this functionality. You could write a custom query parser by copying the existing code and just overriding the timestamp part. An alternative to this would be a configuration knob in the grpc-gateway runtime configuration to enable this special case timestamp parsing, but I'd really prefer not to add such a knob unless there are more users asking for it since there is a workaround.

Let me know if you need any more pointers.
