### ISSUE TITLE
Is there a way for --openapiv2_out to not copy the path to my protofile?

### ISSUE THREAD

**Issue by wangwalton** [grpc-ecosystem/grpc-gateway#1879]
## 📚 Documentation

If I run:
```
protoc -I . --go_out ./ --go-grpc_out ./ \
   --grpc-gateway_out ./  \
   --openapiv2_out ./  \
   src/main/proto/hello.proto
```

The go and grpc_gateway generate code as expected in the specified package folder, but the swagger.json is  generated in `src/main/proto/`. Is there any way to let it be generated in the base directory `./`?

**Comment by johanbrandhorst** [comment]
No, this is not currently configurable. It generates the files relative to the input files because that is how protoc supplies the file paths. We could add something like a `strip-prefix` flag or something to control where the generator should output files to. What can I do to help you bring this contribution in?

**Comment by wangwalton** [comment]
Happy to contribute, but my company has certain restrictions on open source contributions, will check-in in the new years and see if I'm allowed to send in a PR.
