### ISSUE TITLE
What is the recommend way to bind 3rd party APIs (e.g. Health/Check to /healthzf

### ISSUE THREAD

**Issue by micimize** [grpc-ecosystem/grpc-gateway#1931]
## 📚 Documentation

There are docs for [implementing `grpc.health.v1.Health/Check`](https://grpc-ecosystem.github.io/grpc-gateway/docs/operations/health_check/), but I have not been able to find much documentation on how to map 3rd party gRPC services to http methods, especially for standalone servers.

When using Cloud Endpoints, simply adding annotations to copied protos and running `protoc --include_imports ...` worked alright, and likely YAML configuration would have worked as well. However, I have found no straightforward way to generate the 3rd party mappings when running a standalone instance, and have currently resorted to munging generated output into a separate package.

I don't know what other standardized protocols exist in the gRPC ecosystem other than `grpc.health.v1`, so maybe this is worth treating as a special case.

**Comment by johanbrandhorst** [comment]
I'm not sure what you're asking here TBH. What do you mean by 3rd party APIs? The grpc-gateway uses the protobuf file as the source of truth, so anything you want it to translate has to be expressed using protobuf. What do you want to do?

**Comment by micimize** [comment]
@johanbrandhorst `grpc.health.v1` is from `google.golang.org/grpc/health/grpc_health_v1`, an external package defining a protos for servers to implement, and providing `RegisterHealthServer`. I want to proxy `/healthz` from the gateway to `grpc.health.v1.Health/Check`, but the protos are not within my package's domain.

If I copy the protos and generate gateway code from them, it will be incompatible with the code in the health package, because it expects to be embedded within the package itself. So, what should we do when we have external packages that specify protos to implement as part of their API?

**Comment by johanbrandhorst** [comment]
Ah, I see. You can use the so called "gRPC API Configuration" method to create mappings for protofiles you don't own yourself: https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/grpc_api_configuration/. Let me know if those docs aren't clear enough on their own.

**Comment by dgparker** [comment]
Trying to accomplish something similar here myself. The "gRPC API Configuration" method does allow you to generate the `pb.gw.go` file. However, it's references to the generated types go unresolved since the file expects to be included within the same package as the `pb.go` file. The generated gateway will attempt to define something like this:

`var protoreq HealthCheckRequest`
 
In go this results in a compiler error `undeclared name` to fix this in the generated file we'd need to add an import statement of `google.golang.org/grpc/health/grpc_health_v1` and change all the references to 

`var protoreq health.HealthCheckRequest`

I've tried to resolve these issues in multiple ways. Generating the `pb.go` in addition to the `pb.gw.go` file fixes the reference errors but results in namespace conflicts at runtime which are documented [here](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict). 

The only working solution I've actually managed to come up with involves taking complete ownership of the third-party proto file so the references and namespacing play nice with each other. But this is obviously counter productive.

Based on the grpc namespace enforcement it seems like the only proper way to handle this use case is to configure the gateway generator to import and use the package generated in the third-party `pb.go` file. Unfortunately `protoc-gen-grpc-gateway --help` doesn't seem to list any flags that support this currently.

Any insights or potential solutions would be greatly appreciated!

**Comment by johanbrandhorst** [comment]
Hi @dgparker, I understand the issue. Could you try using the `standalone=true` [option](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-grpc-gateway/main.go#L32) when generating the gateway? It'd look something like this:
```shell
$ protoc --grpc-gateway_out ./some_path/ --grpc-gateway_opt standalone=true myfile.proto
```

Or, if you're using [buf](https://github.com/bufbuild/buf), in your `buf.gen.yaml`:
```yaml
- name: grpc-gateway
  opt:
    - standalone=true
```

**Comment by dgparker** [comment]
This is exactly what I was looking for thank you!

The reason why I wasn't finding this is because I was still on v1. Updating my dependencies to v2 resolves this issue and the `standalone=true` generates the code as expected. Amazing! I don't even want to admit how long I wrestled with this :(

Thanks @johanbrandhorst  for the info!

**Comment by johanbrandhorst** [comment]
Always happy to help 😀. To help others avoid this issue in the future, would you be willing to contribute a docs blurb? We could add it to the FAQ and/or gRPC API configuration page.

**Comment by dgparker** [comment]
Most certainly, I'll whip something up and submit a PR.

**Comment by dgparker** [comment]
Opened #1955

**Comment by johanbrandhorst** [comment]
@micimize does this help resolve your initial use case?

**Comment by micimize** [comment]
@johanbrandhorst just tested and indeed it does. Had to mess with output directory to deal with go subdirectory import issues (probably due to a lack of understanding on my part) so I ended up with:
```bash
mkdir -p ./api/grpc_health_v1/
# generate health proxy
protoc -I proto/grpc/health/v1/ -I ./proto/ \
  --grpc-gateway_out ./api/grpc_health_v1/ \
  --grpc-gateway_opt logtostderr=true \
  --grpc-gateway_opt paths=source_relative \
  --grpc-gateway_opt standalone=true \
  proto/grpc/health/v1/health.proto 
```

Thanks y'all!
