### ISSUE TITLE
Undocumented buf beta usage is confusing

### ISSUE THREAD

**Issue by marcusirgens** [grpc-ecosystem/grpc-gateway#2036]
## 📚 Documentation

Hi! I really appreciate this project and we might be using it in our next work project. However, being fairly new to the protobuf ecosystem, the usage of `buf beta mod ...` here caused a lot more confusion than I wished necessary. I can't find a single piece of documentation for it, and it adds a new layer of complexity to running our build tasks that is very hard to understand.

Thanks for an otherwise great tutorial and piece of software!

**Comment by johanbrandhorst** [comment]
Hi Marcus, thanks for your issue. I added the `buf` build instructions because it allows for a modern way of managing protobuf dependencies. Unfortunately, the Buf schema registry itself isn't available publicly, and neither is the documentation we've written (I work at Buf) for it, yet. I completely understand the frustration, but on balance I thought it'd be worthwhile including the minimal setup required to use `buf` for dependency management now that the gateway uses it, than keep only the old `protoc` instructions. We of course kept the old `protoc` instructions as well for users familiar with `protoc`, or those who do not wish to use `buf`.

The Buf schema registry documentation is going to be made public when the beta is released to the public, but if you want to try it out today you can sign up for the private beta waitlist at https://buf.build/waitlist, or reach out to me on the [Buf public Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w), and I'd be happy to answer any questions you have.

In general though, the instructions in this README, coupled with the example available in [the boilerplate repo](https://github.com/johanbrandhorst/grpc-gateway-boilerplate) _should_ be all you need for generic grpc-gateway usage. Let me know if there's anything particular we can add for this workflow that isn't covered, but obviously this isn't the place for generic `buf beta mod` documentation.

**Comment by marcusirgens** [comment]
>  but obviously this isn't the place for generic buf beta mod documentation.

I agree, was mostly meant as a heads up. I look forward to seeing the buf schema repo going live! :)
