### ISSUE TITLE
google.protobuf.Duration: add support for other suffixes ("ns", "us", "ms", "m", "h")

### ISSUE THREAD

**Issue by powerman** [grpc-ecosystem/grpc-gateway#2057]
## 🚀 Feature

Currently values accepted for google.protobuf.Duration must be a string with float seconds with "s" suffix.
I think it would be useful to support same values as time.ParseDuration.

**Comment by achew22** [comment]
@powerman, I love the idea, but unfortunately we're not in charge of the un/marshaller. We just use the [one](https://pkg.go.dev/google.golang.org/protobuf/proto#MarshalOptions) that's released by the protobuf team. Since `google.protobuf.Duration` is a well known type I believe changing this would require modifying the proto language spec which is out of scope for this repo. It seems like a reasonable request though, they might be receptive to it.

Best of luck!
