### ISSUE TITLE
HOW to make validation work for http request as well? 

### ISSUE THREAD

**Issue by crispto** [grpc-ecosystem/grpc-gateway#2068]
I have build a grpc/http sever and I use go-proto-validators to generate validation code,  it works well in grpc with grpc.UnaryInterceptor. 
However, the http requests seems not  pass through the validation function.
Add a http middleware did  not work, because the validation can be done only after the http request has been passed into protobuf data structures, which are implemented by the auto-generated code,  modify every function is obviously meaningless.
Is there a way to solve this problem execpt call validate function manually in every rpc function?

**Comment by adambabik** [comment]
There is no support for go-proto-validator in grpc-gateway as far as I know. And honestly, I don't think it's a good idea to add it here because grpc-gateway is just a reverse proxy. Messages should be validated in RPC methods so however a request is sent - through grpc-gateway or directly - it will always be validated. 

I see how painful it is if you want to validate every incoming Protobuf message but I still think that it would be better to implement it in the methods in your gRPC service rather than in grpc-gateway.

**Comment by crispto** [comment]
thanks,  maybe this is the only choice by far @adambabik
