### ISSUE TITLE
Unable to go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2

### ISSUE THREAD

**Issue by orangemail** [grpc-ecosystem/grpc-gateway#2096]
## 🐛 Bug Report

When I try to execute : go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2

I get the following error : 

go: finding github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: extracting github.com/grpc-ecosystem/grpc-gateway v1.16.0
go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2: module github.com/grpc-ecosystem/grpc-gateway@upgrade found (v1.16.0), but does not contain package github.com/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2

## Your Environment

I using ubuntu 16.04. Even if I try to run this command inside docker container...I get same issue.

**Comment by johanbrandhorst** [comment]
The installation instructions mention the correct way to install the gateway via go get https://github.com/grpc-ecosystem/grpc-gateway#installation. Can you try `go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2`? It's using the first major version because you're not specifying the correct module name.

**Comment by WadeLewis** [comment]
Thank you.  I stumbled upon this as well and that was the solution.  Perhaps this should be included in the readme?  Or maybe this is just specific domain knowledge I should've had.

Thanks again Johan.
