### ISSUE TITLE
how do I make an annotation of the PB file mark as the rest URL: https://www.google.com.hk/search?q=grpcgateway

### ISSUE THREAD

**Issue by cxytz01** [grpc-ecosystem/grpc-gateway#2144]
## 🚀 Feature

Sorry for my poor English.

I have a protobuf file, like this:
```
rpc GoogleSearch (SearchWord) returns (SearchResult) {
}

message SearchWord {
    string q = 1;
}
```

I want to announce it to the REST URL with question mark parameters, like this: www.google.com/search?q={myword}

What should I do?

**Comment by johanbrandhorst** [comment]
Hi! Good question, because this behavior is implicit. Basically, any variables that are not specified as path parameters or body parameters will be parsed from the query parameters.

So in your case, you'll need to add the http annotation like this:

```protobuf
rpc GoogleSearch (SearchWord) returns (SearchResult) {
  option (google.api.http) = {
    get: "/search"
  }
}

message SearchWord {
  string q = 1;
}
```

That should look for the variable `q` in the query parameters. I hope that helps.

If you need more help, please reach out on our Slack support channel, #grpc-gateway on [Gophers Slack](https://invite.slack.golangbridge.org/).

**Comment by cxytz01** [comment]
thank you.
