### ISSUE TITLE
add w3c trace headers to incoming metadata context

### ISSUE THREAD

**Issue by sahejsingh** [grpc-ecosystem/grpc-gateway#2228]
## 🚀 Feature

The generated gateway code calls AnnotateContext to add supported http headers into the context.

The incomingHeaderMatcher filters out non-standard headers. See here
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/context.go#L120

This leads to incoming context not having the standard w3c trace headers (traceparent etc).

You do provide WithIncomingHeaderMatcher and we can roll our own combining it with DefaultHeaderMatcher. This is almost always a second thought or say a bug that needs to be fixed.

So, it would be better if some standard (or say common) headers were taken care of by default.

Here are some of the standard and more common ones found in the wild.
```
		"b3"
		"baggage"
		"traceparent"
		"tracestate"
		"x-b3-sampled"
		"x-b3-spanid"
		"x-b3-traceid"
```

Also, I am sure there is a reason, but are you filtering out headers? The grpc service implementation is not receiving the same header information because of this filtering.

**Comment by johanbrandhorst** [comment]
I believe our existing header mapping is defined at the bottom of the README: https://github.com/grpc-ecosystem/grpc-gateway#mapping-grpc-to-http. If there are additional permanent message headers we should support, I'd happily consider adding them to the automatic translation logic. We already make an exception for translating the `Authorization` header verbatim to gRPC metadata since it's so common. I could see a similar argument being made for some of the headers you mention here. As you probably surmised, the existing header translation happens here: https://github.com/grpc-ecosystem/grpc-gateway/blob/c94081aaefd7099bb31e147d88dac19ca1a827c1/runtime/context.go#L98-L163. The default header matcher is here: https://github.com/grpc-ecosystem/grpc-gateway/blob/c94081aaefd7099bb31e147d88dac19ca1a827c1/runtime/mux.go#L66-L74.

I don't think we would break anyone by adding more commonly used headers to the default header matcher either.
