### ISSUE TITLE
Support pprof tools with runtime.ServerMux

### ISSUE THREAD

**Issue by TamalSaha** [grpc-ecosystem/grpc-gateway#239]
Hi,
I am interested in running pprof tools with GRPC gateway. How can I do that without running a  separate server just for pprof?

Thanks.

**Comment by yugui** [comment]
You can simply import `_ "net/http/pprof"` if you reuse `http.DefaultServeMux`.

`examples/main.go` shows a way to combine `http.ServeMux` with `github.com/grpc-ecosystem/grpc-gateway/runtime.ServeMux`.  However, I should have reuse `http.DefaultServeMux` instead of calling `http.NewServeMux()`.  If you reuse, `import _ "net/http/pprof"` will take effect.

**Comment by TamalSaha** [comment]
Thanks @yugui .

**Comment by jinleileiking** [comment]
Good question. I have the same

**Comment by notobject** [comment]
Good question. I have the same

**Comment by hushyael** [comment]
Can someone provide an example how to run pprof & grpc-gateway? 
Can't find `examples/main.go`

**Comment by johanbrandhorst** [comment]
The first reply tells you all you need to know. If you need more help with pprof, please search the official Go pprof docs.

**Comment by sbodwyer** [comment]
@pepehandsjpg you can time travel back to Oct19 2016 and browse the repo at that point to view examples/main.go 

<img width="1819" alt="image" src="https://github.com/user-attachments/assets/1e459223-0e9f-4984-a2eb-6f32f9cd61d3">
