### ISSUE TITLE
Support YAML OpenAPI/Swagger v2 definition generation

### ISSUE THREAD

**Issue by ccampo133** [grpc-ecosystem/grpc-gateway#2403]
## 🚀 Feature

Currently the `protoc-gen-openapiv2` can output a JSON Swagger/OpenAPI v2 API definition file. It would be nice to have an option to produce a YAML version instead.

One main benefits of YAML over JSON is the support for comments. I originally came here with the intent to suggest a feature of generator plugin to add a `Code generated by protoc-gen-openapiv2. DO NOT EDIT.` header comment to the generated Swagger definition (similar to other protoc compiler plugins). However, I realize that is not possible with JSON.

I also personally find YAML a bit more readable compared to JSON, but that is just personal preference.

**Comment by gozeloglu** [comment]
Hi @johanbrandhorst. I am here because I saw the good first issue tag :) It would be a great support package if the YAML generator will be added. As I saw that @ccampo133 has not started yet implementation. I would like to contribute to this enhancement however I looked at the [protoc-gen-openapiv2/internal/genopenapi/](https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-openapiv2/internal/genopenapi) and I think generator code is a little bit complicated. It would be really hard if only I try to develop this feature and also, it takes long time. That's why dividing into tasks and developing step-by-step will be more easy. What do you think? I definitely want to contribute and help to develop this feature.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your interest! I don't believe anyone else is working on it right now, so I don't think you need to worry about coordinating. As for the implementation, it looks like the JSON marshaling happens here: https://github.com/grpc-ecosystem/grpc-gateway/blob/2b08fa6955ec71c1162e23f11e20e802d9de9073/protoc-gen-openapiv2/internal/genopenapi/generator.go#L146-L163. We'd need to somehow replace this part with a YAML marshaler instead. Maybe you could try playing around with it a bit and see how far you get?

**Comment by gozeloglu** [comment]
Hi @johanbrandhorst. Thank you for your reply. I'll try something as soon as possible.

**Comment by hedhyw** [comment]
It seemed that this issue is forgotten, so I have implemented it today by myself. Please, review.
