### ISSUE TITLE
int64 field in proto is displayed type="string" instead of type="integer"

### ISSUE THREAD

**Issue by horacimacias** [grpc-ecosystem/grpc-gateway#2409]
## 🐛 Bug Report

I have a proto file with a message that has both an int32 and int64 fields.
In the swagger file generated by protoc (using protoc-gen-openapiv2) I get the int32 field rendered as type="integer" which is correct, but the int64 field is rendered as type="string" which I belileve is wrong.

## To Reproduce

1. Create a proto file with int32 and int64 fields. Example:
```proto
message MyRequest {
    int32 userId = 1;
    int64 duration = 2;
}
```

1. Compile the protos using `protoc myproto.proto --openapiv2_out output`
1. Check the resulting swagger file.

## Expected behavior

Both userId and duration fields should be a type="integer"

## Actual Behavior

Only userId (the int32 field in proto) is rendered as type="integer". The other one is rendered as type="string"

## Your Environment

OSX using protoc-gen-openapiv2 v2.6.0

**Comment by johanbrandhorst** [comment]
This is working as intended. JSON as implemented in browsers can represent integers accurately up to 2^53-1 since it represents all numbers as 64bit floating point. Beyond that, it cannot accurately represent integers. This is why the protobuf JSON mapping defines int64's as strings: https://developers.google.com/protocol-buffers/docs/proto3#json.
