### ISSUE TITLE
When using openapiv2_field option on field the "example" parameter doesn't work

### ISSUE THREAD

**Issue by PhilipBehrenberg** [grpc-ecosystem/grpc-gateway#2499]
## 🐛 Bug Report

Using the following example code, both `format` and `pattern` make it into the resulting swagger.json, but `example` does not:

```
message GetRequest {
  string uuid_field = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    format: "uuid",
    pattern: "\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b",
    example: "01234567-89ab-cdfe-0123-456789abcdfe"
  }];
}
```
This is the resulting block for the field, from the swagger.json:
```
{
  "name": "uuid_field",
  "in": "query",
  "required": false,
  "type": "string",
  "format": "uuid",
  "pattern": "\u0008[0-9a-f]{8}\u0008-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\u0008[0-9a-f]{12}\u0008"
}
```

## Expected behavior

What I would expect to see in the swagger.json should be more like:

```
{
  "name": "uuid_field",
  "in": "query",
  "required": false,
  "type": "string",
  "format": "uuid",
  "example": "01234567-89ab-cdfe-0123-456789abcdfe",
  "pattern": "\u0008[0-9a-f]{8}\u0008-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\u0008[0-9a-f]{12}\u0008"
}
```

**Comment by johanbrandhorst** [comment]
Hm, that is strange, since it seems to be working fine in our own examples, see [xx](https://github.com/grpc-ecosystem/grpc-gateway/blob/4fdd9cef3c63030204f35523cfffc49ba8d11a25/examples/internal/proto/examplepb/a_bit_of_everything.proto#L213) and https://github.com/grpc-ecosystem/grpc-gateway/blob/4fdd9cef3c63030204f35523cfffc49ba8d11a25/examples/internal/proto/examplepb/a_bit_of_everything.swagger.json#L3954-L3969. What version of the generator are you using? Could you provide a minimal reproducible example?

**Comment by PhilipBehrenberg** [comment]
I went and made a new project and it worked as expected. The framework I'm using must have some other issue somewhere that is stopping it from working, I'll have to do some more digging. Thank you for your time.
