### ISSUE TITLE
[Question] [Python] Is this repository only for the goland language? Or will it support rest-api in python when making a server?

### ISSUE THREAD

**Issue by psydok** [grpc-ecosystem/grpc-gateway#2503]
- [+] Check if your issue has already been reported (https://github.com/grpc-ecosystem/grpc-gateway/issues).

## I have a question.
Tell me, please, will it be possible to implement gateway on rest-api in python? What will need to be added?
If I make a protofile according to your instructions and generate files in python, will rest-api support be automatically enabled or will I need to add something? Or is this repository only for the goland language?

Tried to find out in several [discussions](https://groups.google.com/g/grpc-io/c/VD0F4Hf6GOw). Silence. 
Bumped into you. 

Someone answered that this python [library ](https://pypi.org/project/grpc-gateway-protoc-gen-openapiv2/)provides file generation for a python client. Is this statement true in the direction of the grpc-gateway service in python?

```
syntax = "proto3";

import "google/api/annotations.proto";

service TestService {
    rpc Method(MethodRequest) returns (MethodResponse) { 
            option (google.api.http) = {
            post: "/api/v1/test"
            body: "*"
        };
    }
}
```

What should be added here?

 ```
 server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    stt_pb2_grpc.add_TestServiceServicer_to_server(
        TestService(), server
    )
    address = f"{host}:{port}"
    server.add_insecure_port(address)
    server.start()
    server.wait_for_termination()
```

Thanks in advance for any answer!

**Comment by johanbrandhorst** [comment]
Hi! It's perfectly possible to use the grpc-gateway with a Python gRPC server, but the gateway itself still needs to be written in Go, since the generated files are in Go. We have an example of a standalone Go binary here: https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/cmd/standalone/main.go. You'll need a bit of Go knowledge to know how to adapt it to your own code, but the rest of your gRPC service can be written in Python.

Hope that answers the question, let me know if you need any other guidance!
