### ISSUE TITLE
Default query parameter parsing behaviour change

### ISSUE THREAD

**Issue by MikeSouza** [grpc-ecosystem/grpc-gateway#2632]
## 🐛 Bug Report

The behavior when parsing duplicate query parameters has changed between v1 and v2.

For example in v1, making the `GET` request `/v2/example/echo?value=foo&value=bar` will log an error `too many field values: name` but return a HTTP 200 status code and response `{ "value": "foo" }`.

However, in v2 when making this same request, it will return an HTTP 400 status code and the error with message `too many values for field "value": foo, bar`.

We expected v2 to behave like v1 after upgrading since this change was not documented in the [v2 Migration Guide](https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/). We have a client using our v1 gRPC Gateway that cannot be changed easily and it is sending duplicate query parameters but it is OK that the duplicate query parameters are ignored/ discarded.

The only way we can get v2 to behave like v1 is to set our own custom query parser via `runtime.SetQueryParameterParser()` but this requires us to copy verbatim most of the code in `runtime/query.go` [minus these few lines of code](https://github.com/grpc-ecosystem/grpc-gateway/blob/v2.10.0/runtime/query.go#L119-L121)... Not ideal!

Pertinent [v1 lines](https://github.com/grpc-ecosystem/grpc-gateway/blob/v1/runtime/query.go#L123-L125) where it doesn't behave this way.

It would be nice if we could opt-out of this behavior. If this is a feature you're willing to support, I can make a PR implementing it.

## To Reproduce

1. Run the example gRPC server and gateway.
2. Make the `GET` request `localhost:8080/v2/example/echo?value=foo&value=bar`

## Expected behavior

See above.

## Actual Behavior

See above.

## Your Environment

N/A

**Comment by johanbrandhorst** [comment]
Hi Mike, thank you for your issue. I'm sorry that this was a surprising change of behavior, and you are correct that we should update the migration guide to highlight this behavioral change. As for turning this behavior back on again.. this is arguably a bug fix. Since there is already a workaround (as outlined by yourself) I'm tempted to say that we should do nothing here. I know what's probably not what you want to hear but I'm sure you can appreciate that we try to be conservative with new additions to the tool since every new option adds overhead to all users.

**Comment by MikeSouza** [comment]
@johanbrandhorst Hi Johan, thanks for the response.

I can understand not wanting to maintain another option for such.

My alternative proposal would be to make the [struct `defaultQueryParser`](https://github.com/grpc-ecosystem/grpc-gateway/blob/v2.10.0/runtime/query.go#L39) exported.  Currently the main issue we have with the workaround is having to maintain a fork of the `runtime/query.go` and `runtime/query_test.go` where it's like 99% copypasta'd the code in these files.  It would be much easier for us if the default query parser was exported so that we can wrap it and provide our own custom behavior. What do you think about this?

**Comment by johanbrandhorst** [comment]
Thinking about it for a moment, I think we could probably do that, since the reason we'd want to keep it private is so that we can make changes to it, but we're already bound by the interface and the existing behavior so we probably can't make any changes anyway. Would you be willing to contribute this?

**Comment by MikeSouza** [comment]
> Thinking about it for a moment, I think we could probably do that, since the reason we'd want to keep it private is so that we can make changes to it, but we're already bound by the interface and the existing behavior so we probably can't make any changes anyway. Would you be willing to contribute this?

Thanks! PR #2651 submitted.
