### ISSUE TITLE
Nix Flake

### ISSUE THREAD

**Issue by thegergo02** [grpc-ecosystem/grpc-gateway#2767]
[I've created a Nix flake for reproducible builds.](https://github.com/thegergo02/grpc-gateway-flake)
It's up to the maintainers if they care about Nix and want to document this.
(I've created it for the sole reason of bringing another project to Nix.)

**Comment by johanbrandhorst** [comment]
Hi, this is really cool! I'm a little confused though, because it doesn't look like the nix definitions build either of our primary binaries, `protoc-gen-grpc-gateway` and `protoc-gen-openapiv2`. Am I missing something?

Also, even though I use nixos personally and am a fan of the project, I doubt this is something we'll want to support. Happy to point people to your repository if someone asks though.
