### ISSUE TITLE
Documentation for NodeJS

### ISSUE THREAD

**Issue by hashweather** [grpc-ecosystem/grpc-gateway#3013]
Thanks guys for this.

However, almost the entire documentation is about Golang. I understand the love for Golang but can you guys be nice as to add support for NodeJS as well.

I have spent hours trying to expose some of my NodeJS functions over REST by following your documentations but it has all been futile.

I am on a MacOS and so I tried downloading the binaries but I couldn't see any MacOS compatible binaries.

Any documentation for NodeJS will really help.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your interest in the project! The [boilerplate project](https://github.com/johanbrandhorst/grpc-gateway-boilerplate) is designed to show an example of how to use the gateway in front of an arbitrary gRPC server. Unfortunately you'll always have to have part of your application built with Go, since the code generator only supports Go, but if you look at the example, you can imagine the `gateway` package being used without first starting the Go gRPC server. See https://github.com/johanbrandhorst/grpc-gateway-boilerplate#running-the-standalone-server for an example of how to run it.

As for the releases, the `darwin` releases are built for MacOS: https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.13.0. I'm not sure if MacOS will let you run them without overriding some safety settings since they're not notarized, but there's not much we can do about that without adding a lot more work and cost for us AFAIK.

Let me know if you need anymore help, and feel free to drop by our Slack channel (#grpc-gateway on [Gophers Slack](https://invite.slack.gobridge.org)) if you want more synchronous help.
