### ISSUE TITLE
Swagger request definitions not being generated when field from proto is in path

### ISSUE THREAD

**Issue by iancharters** [grpc-ecosystem/grpc-gateway#3038]
## 🐛 Bug Report

When trying to generate swagger from protos, I am unable to generate the request definitions for any route that uses the id in the path.  I've tested this theory by removing {thing_id} from the path and everything seems to generate as normal.  My expectation is that a swagger definition is created from the UpdateThingRequest proto message with the ID removed.  Instead, it doesn't generate that swagger definition at all and inlines all the non-ID fields as parameters in that route.

## To Reproduce

Generate a swagger spec from a spec that looks something like the following:

```
message UpdateThingRequest {
  string thing_id = 1;
  OtherField1 o1 = 2;
  OtherField2 o2 = 3;
  ...
}

message UpdateThingResponse {
...
}

service ThingService {
  rpc UpdateThing(UpdateThingRequest) returns (UpdateThingResponse) {
    option (google.api.http) = {
      patch: "/things/{id}"
      body: "*"
    };
  }
}
```

## Expected behavior

The /things/{thing_id} route would have a reference to an UpdateThingRequest definition, which looks like the proto message of the same name minus the ID field.

## Actual Behavior

While UpdateThingResponse is generated and referenced, UpdateThingRequest is not referenced or even generated for that matter in the /things/{thing_id} route.

## Your Environment

Go 1.19.1 darwin/arm64, MacOS

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! Could you share your protobuf definitions and generated swagger file? I think I know what's going on but want to confirm. Basically, whenever there's a field of your request message in the path, the swagger generator will not reference the message type itself, but inline all the fields of the message that _aren't_ in the path. This is the correct behavior, since if the field is specified in the path and the body, the body is ignored. Is that the behavior you are seeing?

**Comment by iancharters** [comment]
Hi @johanbrandhorst,

That is indeed the behaviour I'm seeing.  What I want is for it to create a swagger definition of that request without the ID field and reference it instead of inlining all of the proto message fields into the path.  

The reason for this is because we do some tricky document stitching where we convert the swagger models into OAS3 models and then reference them directly in another document in order to prevent drift between the gateway's models and the internal service's models.  We don't copy the paths over so I don't have the reliability of always having the correct generated request.

I suppose a way around this is to create a dummy route that has a proto message in it that includes all of the models I want to be outputted, but that's pretty hacky and would like to avoid if at all possible.

**Comment by johanbrandhorst** [comment]
I see. There is nothing in the gateway to support the behavior you seek, and actually, I would generally recommend having different definitions for your internal and external APIs (if I'm understanding you correctly). Protobuf isn't a language where DRY applies very much, since liberty to evolve the schema is much more important, usually.

I'm satisfied that the gateway is doing the expected thing here, so I'm going to go ahead and close the issue, but let me know if you need anymore help or advice!

**Comment by iancharters** [comment]
The gateway is largely passthrough for many internal services and so we need to ensure our external interfaces are always pegged to our internal ones.  It's a headache managing otherwise.  It's an unusual use case, fair enough, but the argument doesn't quite hold water for me.  If it's truly the case that you should be inlining the model into the endpoint request model, then why not do the same with responses?

Regardless, thanks for your help, we'll find a different way to accomplish this.
