### ISSUE TITLE
path parameters are overwritten by query parameters with the same name 

### ISSUE THREAD

**Issue by ljmsc** [grpc-ecosystem/grpc-gateway#3069]
## 🐛 Bug Report

if you have path parameter in your proto endpoint definition, you can overwrite the value by setting a query parameter with the same name. This is a security issue in my opinion since a gateway or routing rule maybe only checks the path but not the query parameters.

## To Reproduce

The following service definition given:
```
service MyService {
  rpc GetResource(GetResourceRequest) returns (GetResourceResponse) {
    option (google.api.http) = {
      get: "/admin/{resource_id}"
    };
  }
}
```
One can call the API with `GET <host>/admin/<some_resource_id>` and gets the resource back. But it is also possible to call the endpoint like this:  `GET <host>/admin/<my_resource_id>?resourceId=<some_other_resource_id>`

In the GRPC Handler the value of resource_id is set to <some_other_resource_id> instead of <my_resource_id>

## Expected behavior
It should not be possible to overwrite path parameters with query parameters.

## Actual Behavior
It is possible to overwrite path parameters with query parameters.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue report. Could you share an example of this? I did some quick code spelunking and it seems to me that values that are specified in the path are added to the query parameter filter appropriately:
1. See definition of `Custom` rpc here: https://github.com/grpc-ecosystem/grpc-gateway/blob/1e64a415b0d3abc69bb164107ae46d9769293867/examples/internal/proto/examplepb/a_bit_of_everything.proto#L575-L579. It defines `uuid` to be part of the path.
1. This is the generated code: https://github.com/grpc-ecosystem/grpc-gateway/blob/1e64a415b0d3abc69bb164107ae46d9769293867/examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go#L760. `uuid` is added to the filter.
1. This filter is used in `PopulateQueryParameters` to skip parsing of this value: https://github.com/grpc-ecosystem/grpc-gateway/blob/1e64a415b0d3abc69bb164107ae46d9769293867/runtime/query.go#L56.

If this bug report is accurate I'd suspect a problem with the filter. It also strikes me as possible that you could construct a query parameter using the json name instead of the proto name and bypass the filter. Could you confirm whether `resourceId` also works?

**Comment by ljmsc** [comment]
hey @johanbrandhorst you are actually right. You need to define `resourceId` as query param to overwrite the `resource_id`. That was wrong in my example above. That is also the reason why the `HasCommonPrefix()` function does not detect the field because the json name differs from the actual field name.

**Comment by johanbrandhorst** [comment]
OK, then I both understand the issue and the cause. The query parameter parser is intentionally lenient in the parsing of query parameters, but clearly that is causing this problem. Removing the parsing of json name query parameters would be a breaking change, and although I'm happy to do that for what could arguably be considered a security issue, I think we should just make the filter look for both the protobuf and json name format. We can modify the gateway generator to output both the proto name and json name into the double array, which should fix the issue. Would you be willing to help contribute this fix?

**Comment by ljmsc** [comment]
hey @johanbrandhorst, I would like to help providing a fix for that. 👍 I‘ll give it a try.

**Comment by johanbrandhorst** [comment]
I think we need to add the jsonName to this line: https://github.com/grpc-ecosystem/grpc-gateway/blob/1e64a415b0d3abc69bb164107ae46d9769293867/protoc-gen-grpc-gateway/internal/gengateway/template.go#L142.

**Comment by ljmsc** [comment]
there we go #3072
