### ISSUE TITLE
unit return code 

### ISSUE THREAD

**Issue by bourne-3** [grpc-ecosystem/grpc-gateway#3259]
## 📚 Documentation
In the business we need the return code in the following format
```
{
  data:【proto return 】,
  msg:ok,
  code:200
}
```
I find https://github.com/grpc-ecosystem/grpc-gateway/issues/1051#issuecomment-536627358 propose way to deal
However,The format returned is not ideal. Like below
```
{
    "code": 0,
    "msg": "success",
    "data": {
        "isSucc": false
    }
}{
    "isSucc": false
}
```
I looked at the source code and found that it was caused by the following
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/59307069/227474484-70335514-0689-4574-90ca-a77b2efe0e6a.png">

Is there any way to just get the format i except,

**Comment by johanbrandhorst** [comment]
Yeah you'll need a custom marshaler for this, not writing the content you want in `ForwardResponseOptions`. You could create a marshaler that wraps the default marshaler with your extra JSON quite easily, I think. If you need more help with this please reach out on our support channel (#grpc-gateway on Gophers Slack), since this is not an issue with the gateway, I'm going to close it.
