### ISSUE TITLE
utilities.IOReaderFactory is inefficient

### ISSUE THREAD

**Issue by leungster** [grpc-ecosystem/grpc-gateway#3714]
## 🐛 Bug Report

`utilities.IOReaderFactory` relies on `io.ReadAll` which is [documented to be inefficient](https://github.com/golang/go/issues/50774) for large inputs. 
For our use case, we had a 200MB JSON body that resulted in > 5GB transient memory allocations. 

It looks like in most cases, the `req.Body` could be passed directly into the marshaler. The exception to that is when field_masks are used then the body is parsed twice.  

## To Reproduce

Create a proto definition with repeated fields and send a relatively large input payload to monitor memory utilization. 

## Expected behavior

Memory utilization doesn't grow several times the input size. 

## Actual Behavior

Our 200MB input turned into more than 5GB memory allocations that the GC had to reclaim. This transient explosion in memory usage causes our service to run out of memory.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue report. I'm sorry to hear that you had a bad experience. I think there is something we can do here. We introduced the `IOReaderFactory` to support patch requests, but we don't really need it if the user doesn't enable the patch feature. Here is the relevant logic: https://github.com/grpc-ecosystem/grpc-gateway/blob/6dff99462f4a0ffe4589a167d37316038e48673c/protoc-gen-grpc-gateway/internal/gengateway/template.go#L336-L354. I think we could rewrite this so that we only created a reader factory if `$AllowPatchFeature` is true, and in other cases we can use `req.Body` directly. Would you be willing to make such a contribution?

**Comment by leungster** [comment]
I went ahead and made the change https://github.com/grpc-ecosystem/grpc-gateway/pull/3727
