### ISSUE TITLE
Invalid conversion between json and protobuf

### ISSUE THREAD

**Issue by nlamirault** [grpc-ecosystem/grpc-gateway#396]
I've got an error to convert between json and protobuf.
First i think it's due to *jsonpb* : https://github.com/golang/protobuf/issues/347.
Do you have any idea ?
Thanks.

**Comment by TamalSaha** [comment]
@yugui , mind taking a look at this one?

**Comment by yugui** [comment]
Sure.
It was a kind of intentional limitation. But I'm open to supporting arrays of messages under certain conditions.

To be short, it is not supported because it is prohibited by the spec of `google.api.HttpRule` (https://cloud.google.com/service-management/reference/rpc/google.api#google.api.HttpRule.FIELDS-table). But nowadays grpc-gateway supports some extension to the spec. So it is not a bad idea to support arrays of messages if we have a reasonable concrete use case. 
Also, it might be a good opportunity to clarify what is specific to grpc-gateway and what is common to other implementations like Cloud Endpoints.

**Comment by achew22** [comment]
@yugui, do you have a list of places where we have deviated from the spec? Sounds like you have some in mind. I've been trying very hard to be faithful to the spec and I woud like to know what I'm missing.
