### ISSUE TITLE
The API Gateway Vision

### ISSUE THREAD

**Issue by lhdhtrc** [grpc-ecosystem/grpc-gateway#4117]
## 🚀 Feature
Why do you raise this question?
- The microservice gateway component is required to control all microservice components

Project structure:
- Each grpc proto is a separate microservice component
- Each microservice component is a separate project

Core functions that have been implemented:
- etcd as the registry
- [grpc proxy grpc](https://github.com/mwitkow/grpc-proxy)

Unimplemented core functionality:
- http proxy grpc

Here refers to the http proxy grpc, in fact, the GRPC-gateway has been implemented, but there is a problem is that each time a microservice component is added, the microservice gateway component needs to modify the code (because the GRPC-gateway of the new microservice component is registered in it).
This means that every addition of a grpc microservice component requires a change to the microservice gateway, which is very silly.
Therefore, I want to ask whether there is a method in GRPC-gateway to achieve dynamic implementation of http proxy grpc;
The idea is that gin middleware intercepts routes that hit microservice rules (e.g., GET:/micro/app) and forwards them to the internal grpc proxy grpc.(A clear and concise description of what the feature is.)

**Comment by johanbrandhorst** [comment]
Hi. If I'm understanding you correctly, you'd like to have the gateway be able to dynamically redirect requests rather than have to regenerate and recompile the gateway every time a new service is added?

This isn't possible with the grpc-gateway, but there are other tools that support this sort of thing, such as https://github.com/connectrpc/vanguard-go.

**Comment by lhdhtrc** [comment]
@johanbrandhorst thanks
