### ISSUE TITLE
an google.protobuf.Any type how to get openapiv2 output?

### ISSUE THREAD

**Issue by dobet** [grpc-ecosystem/grpc-gateway#4135]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I have an field
```
message Test1 {
    string name = 1;
}

message Test2 {
    repeated string names = 1;
}

message Reply {
    google.protobuf.Any Data = 1;
}
```
sometimes Reply.Data is Test2.name, sometime Reply.Data is names,
when I gen openapi.json, Reply.Data is error . 

What can I do?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. `google.protobuf.Any` fields are not great for JSON translation. You may want something like `google.protobuf.Struct` instead - this type allows arbitrary JSON. Note that it's not a great experience for users (as you noticed). I recommend having strictly typed responses for each endpoint, instead of one that varies.
