### ISSUE TITLE
Log level for errors is "info"

### ISSUE THREAD

**Issue by rosemary-wang** [grpc-ecosystem/grpc-gateway#4245]
Hi team, I have a question regarding the[ log level ](https://github.com/grpc-ecosystem/grpc-gateway/commit/a5b66c16bab6156b1cc525e76159bdff463123ba) chosen for the generated code. I noticed that `info` level is used for everything, even for obvious errors such as "failed to decode message". I'm curious about the motivation behind this choice. Thank you!

**Comment by johanbrandhorst** [comment]
Hi Rosemary, thanks for your issue! I don't think the log level of these messages have changed since they were first introduced, and I doubt the level was considered much. If you have any thoughts on ways to differentiate different log messages, it might make for a great contribution! The logic for the generated file is mostly here: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-grpc-gateway/internal/gengateway/template.go.

**Comment by rajeshkarnena** [comment]
Hello @johanbrandhorst @rosemary-wang, can I help with a PR for this? 

I also noticed that a few log statements in the package [runtime](https://github.com/grpc-ecosystem/grpc-gateway/tree/main/runtime) did not follow the correct log level, e.g., [this one](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/handler.go#L89) and [this one](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/errors.go#L117). Is that intentional?

**Comment by rosemary-wang** [comment]
i haven't started working on this so feel free to take it

**Comment by johanbrandhorst** [comment]
Feel free to open a PR

**Comment by rajeshkarnena** [comment]
Here you go, please review #4327
