### ISSUE TITLE
Adding authentication definitions to generated swagger files

### ISSUE THREAD

**Issue by boosh** [grpc-ecosystem/grpc-gateway#428]
My API requires authentication for all endpoints. This is defined in a `config.yml` file that I feed into Google Cloud Endpoints. 

I generated a swagger spec from my service's .proto file, and then generated a javascript library for use on the web. 

Do you have any plans to support swagger's [API keys](https://swagger.io/docs/specification/authentication/api-keys/) definitions, or should we monkey-patch them into generated libraries ourselves (if that's even an optionI)?

**Comment by c4milo** [comment]
I had the same issue and I've been monkey patching.

**Comment by achew22** [comment]
@boosh, right now we don't support this since we don't emit OpenAPIv3 definitions. You're welcome to monkey patch it, or to take this opportunity to extend on the work of Ivan and help us by adding support for the subset of OpenAPIv3 you're interested in using. If you want some pointers on that I'm happy to help!

**Comment by ivucica** [comment]
This exists in v2 as well: https://swagger.io/docs/specification/2-0/authentication/api-keys/

We'd need to add `security` field into `grpc.gateway.protoc_gen_swagger.options.Operation`. We'd also need to add `security` and `securityDefinitions` into `grpc.gateway.protoc_gen_swagger.options.Swagger`.

**Comment by ivucica** [comment]
I hope this is what you had in mind :-)
