### ISSUE TITLE
REST API without proxying

### ISSUE THREAD

**Issue by crackcomm** [grpc-ecosystem/grpc-gateway#46]
Hello. I think it is a little wasteful to parse JSON then create a protobuf message and again parse it, rather than just parse the JSON into protobuf structure. Services could perform a little slower when parsing big amounts of JSON but I think overall cost would be reduced. Please tell me what do You think about this idea.

**Comment by yugui** [comment]
I guess the idea requires the gateway to run in the same process as the wrapped gRPC service.

It can be useful and patch is welcome if it is compatible enough to ordinal gRPC services.
But I have no plan to work on that because of two reasons.
1. it is not a bottleneck for us
2. Needs changes to grpc-go itself to keep `"google.golang.org/grpc".SendHeader` compatible to the ordinal call flow.

**Comment by crackcomm** [comment]
Second reason makes it clear, after taking a look into `grpc.SendHeader` code it seems that it would require more changes in grpc-go than expected.

Thank You @yugui

**Comment by jimbojetlag** [comment]
Oh, too bad. I had the impression that there is a no proxy option. Guess grpc-gateway never works on App Engine :(

**Comment by achew22** [comment]
Just doing a little bit of tidying. I hope that your question was answered in a way that let your project continue. If you have any more questions feel free to open another issue.
