### ISSUE TITLE
Prefixed model names in generated swagger spec

### ISSUE THREAD

**Issue by lukasmalkmus** [grpc-ecosystem/grpc-gateway#525]
Why are the models in the swagger spec prefixed with the last bit of the proto package name? Is there a reason for this? I find this pretty ugly tbh and don’t see the advantage.

**Comment by achew22** [comment]
The reason to generate the prefixes is that we don't have a guaranteed unique namespace. If two packages produce different `Foo` messages then we will have trouble.

> Why not strip the prefix if it isn't necessary? (the next obvious question)

I tried that, but the problem is that if you do that then when you add a message in that happens to conflict it will break code that is very far away from the code that changed. This is in an effort to adhere to [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

If you disagree with me, I would love to hear your reasoning why. Maybe we will even change it to work the other way! I'm happy to answer any more questions you might have about the project. Since I've gotten this question a couple of times in various ways, I'm also going to add a FAQ entry list to the README.md in the root. Feel free to send PRs to enhance that (even if it is only a question, I can propose a change on top of your PR that has the answer and we can merge it!)
