### ISSUE TITLE
No out-of-the-box way to unmarshal json with grpc gw error

### ISSUE THREAD

**Issue by sknaumov** [grpc-ecosystem/grpc-gateway#530]
I want to unmarshal json-formatted error returned by grpc-gateway and create gRPC Status object. The problem is that there is no out-of-the-box helper for it, and if to do it by hands, I need to replicate errorBody struct to do it.

Could you please provide default helper or make errorBody public?

**Comment by achew22** [comment]
I'm not sure I understand what you're attempting to do here. Do you think you could elaborate a little bit more. Maybe giving an example would help

**Comment by sknaumov** [comment]
I'm trying to convert an error reported by grpc-gateway back to grpc one:

```go
package gateway

import (
	"encoding/json"
	spb "google.golang.org/genproto/googleapis/rpc/status"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"io"
	"net/http"
)

/* Similar type is defined in grpc-gateway package, but it is not exported */
type errorBody struct {
	Error string `json:"error"`
	Code  int32  `json:"code"`
}

func HTTPgRPCError(r *http.Response) error {
	if r.StatusCode == 200 {
		return nil
	}
	if r.Header.Get("Content-Type") == "application/json" {
		if s, err := JSONBodyToStatus(r.Body); err == nil {
			if e := s.Err(); e != nil {
				return e
			}
		}
	}
	return status.Error(codes.Unknown, r.Status)
}

func JSONBodyToStatus(body io.Reader) (*status.Status, error) {
	var e errorBody
	if err := json.NewDecoder(body).Decode(&e); err != nil {
		return nil, err
	}
	return status.FromProto(&spb.Status{Code: e.Code, Message: e.Error}), nil
}
```

**Comment by achew22** [comment]
Why do you want to route through gRPC gateway instead of directly connecting to the service in question? It seems like the layer of indirection may not be necessary.

**Comment by llimllib** [comment]
The problem is that I can't send an invalid request to the service in question (in my case, an integer for an enum that is invalid), the response is of a type that I am not able to marshal into a struct without copying `errorBody` into my own code.

It would be better if `errorBody` were public so I could write an integration test that the return value of my endpoint were a `gateway.ErrorBody` if there was an error; in fact I wish the swagger output for my API would document that as well.

**Comment by achew22** [comment]
@llimllib, could you elaborate on what you mean by "send an invalid request to the service"? Is that a gRPC service or a REST service? Who is determining that the request was invalid? Is this gRPC validation logic or your service's validation logic or even gRPC gateway's?

If you would like to see something made public, I would recommend a PR so that we can discuss the specifics of your proposal. If you need any help with that at all, please comment in here and I'd be happy to help! :smile:

**Comment by llimllib** [comment]
@achew22 sure, here's what I mean:

* Endpoint A accepts an enum attribute, let's call it `foo`, whose valid values are `0`, or `1`, let's call their names `ALPHA` and `BETA`
* GRPC Gateway says that `foo` is a string, but it also accepts integers
  * (is this a bug?)
* If I pass `GAMMA` to the endpoint for attribute `foo`, I get an error from grpc as I expect
* If I pass `30` to the endpoint, I do not get an error and the invalid value gets passed to the handling function
  * Now I need to test that invalid values that reach my function (which seem to me like they should be a type error in the first place) return an error that I expect them to return
  * This is why I need to use `errorBody`

I will try to make a reproducing example, but I may not have the time. I apologize for that

**Comment by johanbrandhorst** [comment]
@llimllib I'm not sure what the error case has to do with knowing the structure of errorBody, that only concerns clients of the API? Your gRPC server doesn't need to do anything about it or worry about its structure. Am I misunderstanding something?

As for the enum translation, I haven't looked at the code recently but I believe this is configured in your JSON marshaller, and not the gateway (except for query parameters, which are always handled by the gateway code).

**Comment by llimllib** [comment]
OK, you're right and I traced the enum issue (which is annoying) to `jsonpb`, it's basically https://github.com/golang/protobuf/issues/174

(Oddly, grpc-gateway handles this case differently than `jsonpb`, and it is the way I expect. I wrote up the test case I gave above, and here's the output from grpc-gateway:

```
$ curl 'http://localhost:1235/hello?enumValue=1'; echo
{"response":"BETA"}
$ curl 'http://localhost:1235/hello?enumValue=2'; echo
{"error":"2 is not a valid main.Test","message":"2 is not a valid main.Test","code":3}
```

I don't know why `jsonpb` can't handle this the same way!)

And the reason I'd like `errorBody` to be public is to write an integration test for that case; if the enum value is passed in as `2`, but `jsonpb` doesn't produce an error, I want to verify that my endpoint returns an error in the standard grpc-gateway format by deserializing it into an `errorBody`; because it's not public I have to copy the struct into my integration test code.

Not the biggest problem in the world, but an annoyance.

**Comment by johanbrandhorst** [comment]
I see, yes, well, the proper way to do this might be to implement an alternative error return in the generated swagger definitions. We did a similar thing for streamed returns recently: https://github.com/grpc-ecosystem/grpc-gateway/commit/f336fbcc3f21acf89e935c2353e7ead734ec31f5. Would you be interested in contributing something like that?

**Comment by llimllib** [comment]
phew, I would like to but I would rate myself as extremely intimidated by reading that PR

**Comment by johanbrandhorst** [comment]
I think it would mostly be hardcoding new things into the swagger generator template tbh; especially since the format of error body is constant. Many of the files in that change just concern generated test files, the meat of the changes are in `protoc-gen-swagger/genswagger/generator.go` and  `protoc-gen-swagger/genswagger/template.go`. Let me know if you need more help :). You could join the #grpc-gateway channel on the gophers slack for more immediate feedback.
