### ISSUE TITLE
Source code still imports "golang.org/x/net/context"

### ISSUE THREAD

**Issue by logicaleak** [grpc-ecosystem/grpc-gateway#533]
Hi there,

I am trying to set up grpc-gateway for our project in golang 1.9. As you know ```golang.org/x/net/context
``` is no longer there in this version, however the source code that needs to be included for the imports in the proto file, still tries to import ```golang.org/x/net/context```. I am not sure how to move forward to fix this issue, any ideas ? (Except ```go get golang.org/x/net/context```)

**Comment by achew22** [comment]
That's probably the best way to go forward today. For now we maintain compatibility with the 2 latest versions of Go. Fortunately [Go 1.10](https://tip.golang.org/doc/go1.10) is expected out in Feb which is pretty soon. When that's released we will migrate to the built in context package and this shouldn't be an issue any more.

Thanks so much for filing an issue! Without field reports we have no idea the things we need to focus on. I'm going to close this since we are already tracking this in https://github.com/grpc-ecosystem/grpc-gateway/issues/326 which I'm itching to close :smile:.
