### ISSUE TITLE
proto: no slice oenc for *reflect.rtype = []*reflect.rtype

### ISSUE THREAD

**Issue by srenatus** [grpc-ecosystem/grpc-gateway#551]
Hey there

With the introduction of error details in JSON responses, #515, we've also gotten us an extra line of output for every JSON error encoding process:

```
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
```

...irregardless of whether this error contains error details or not. Looking back at [the PR's CI run](https://travis-ci.org/grpc-ecosystem/grpc-gateway/builds/327578972), it has been in there [right from the start](https://travis-ci.org/grpc-ecosystem/grpc-gateway/jobs/327578983#L916).

The line comes from [`proto.(*Properies).setEncAndDec`](https://github.com/golang/protobuf/blob/bbd03ef6da3a115852eaf24c8a1c46aeb39aa175/proto/properties.go#L342), called via [`jsonpb.jsonProperties`](https://github.com/golang/protobuf/blob/bbd03ef6da3a115852eaf24c8a1c46aeb39aa175/jsonpb/jsonpb.go#L1027).

However, since the tests pass, it seems like whatever is happening there wouldn't have to happen?

Have you got any idea how to get rid of that?

(While looking into this, I've also started wondering why grpc-gateway's error details don't have `@type` fields, but that's a different matter. But would _you_ think they should have them?)

**Comment by achew22** [comment]
Is this log output, or is it included in the actual output of the server?

**Comment by srenatus** [comment]
It goes to the server's stderr [here](https://github.com/golang/protobuf/blob/bbd03ef6da3a115852eaf24c8a1c46aeb39aa175/proto/properties.go#L336).

**Comment by itizir** [comment]
Hi! Oh yeah, was wondering about this the other day too... Nice one with `Any`, but it's still not fixing it because it should be pointers, not values! :)

Also the protobuf tag would need to contain `rep`, since it's a slice, for it to work properly.

But actually, if `errorBody` needs to be a `proto.Message`, why don't you define it through the protobuf generator?
```
syntax = "proto3";

import "google/protobuf/any.proto";

message ErrorBody {
    string error = 1;
    int32 code = 2;
    repeated google.protobuf.Any details = 3;
}
```

And then by the way it would indeed be nice to unify with the stream errors. :)
https://github.com/grpc-ecosystem/grpc-gateway/issues/538
