### ISSUE TITLE
gRPC gateway Bazel build rules

### ISSUE THREAD

**Issue by achew22** [grpc-ecosystem/grpc-gateway#66]
I'm using the normal bazel go rules (http://bazel.io/docs/be/go.html) and I've started looking into creating a build rule for Bazel so the output from grpc-gateway can be depended upon directly. I have a sneaking suspicion that you're using Bazel in some of your projects. Do you have any tricks/tips for getting everything set up in Bazel? Would you be willing to put a sample in the examples folder of how you're doing this?

**Comment by yugui** [comment]
@achew22 No, I don't have a good example since I am just trying Bazel in a small project which does not use grpc-gateway.
But I agree that it would be useful if we have a Skylark macro like `grpc_gateway_library` or `grpc_gateway_binary`

**Comment by ivucica** [comment]
The following is from a project that's not opensourced (yet), so I can't point to the exact rules. One limiting factor is that I also have custom Go rules (based on Kythe's rules) and haven't gotten around to reworking Bazel's Go rules (see bazelbuild/bazel#828). Because the build rule for `//vendor:protoc-gen-gprc-gateway` is too dependent on custom Go rules that are too fragile and messy to be shared, I'm not sharing them here.

Instead I'll try to describe my approach enough to get interested people started.

This is my `genrule()` in the `BUILD` file for the Bazel package containing file `scheduler.proto`:

````python

genrule(
    name = "scheduler_pb_gw",
    srcs = [
        "scheduler.proto",
        "//vendor:github.com/gengo/grpc-gateway/third_party/googleapis/google/api/annotations.proto",
        "//vendor:github.com/gengo/grpc-gateway/third_party/googleapis/google/api/http.proto",
        "//vendor:github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto"],
    outs = ["scheduler.pb.gw.go"],
    cmd = (
        "$(location @protobuf//:protoc) " +
        " --grpc-gateway_out=logtostderr=true:$$(dirname $@)" +
        " -I$$(dirname $$(dirname $$(dirname $(location //vendor:github.com/gengo/grpc-gateway/third_party/googleapis/google/api/annotations.proto)))):$$(dirname $$(dirname $$(dirname $(location //vendor:github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto)))):." +
        " --plugin=protoc-gen-grpc-gateway=$(location //vendor:protoc-gen-grpc-gateway)" +
        " --proto_path=$$(dirname $(location scheduler.proto)):$$(dirname \"$@\")" +
        " $(location scheduler.proto); mv \"$$(dirname \"$@\")\"/scheduler/\"$$(basename \"$@\")\" \"$@\""),
    message = "Processing proto file with grpc-gateway",
    tools = [
        "@protobuf//:protoc",
        "//vendor:protoc-gen-grpc-gateway",
    ]
)
````

The `WORKSPACE` defines external repository `protobuf`. While ordinarily one would specify a `git_repository()` rule, I am already using vendoring + externals:

````python
local_repository(
    name = "protobuf",
    path = __workspace_dir__ + "/vendor/github.com/google/protobuf",
)
````

I'm using a `genrule()` here because it was easier than writing a proper Skylark rule. Even this `genrule()` is quite hacky.

**Comment by yugui** [comment]
@ivucica Thank you for sharing that.

Although I'm not going to write the skylark rule by myself very soon, but it is definitely on my to-do list.
Also I'm happy to accept PRs for the rule. In both cases, your `genrule` will be quite helpful.

**Comment by pcj** [comment]
I've posted a preliminary implementation of [grpc_gateway_proto_library](https://github.com/pubref/rules_protobuf/tree/master/bzl/grpc_gateway) in rules_protobuf that:

* builds the grpc-gateway runtime and associated libraries, 
* builds the protoc-gen-grpc-gateway plugin, 
* invokes the plugin
* compiles the *.pb.gw.go files into a go_library

Hopefully we can accomplish easy grpc-gateway support in bazel.  Feedback or contributions welcome.
