### ISSUE TITLE
how to use this in java?

### ISSUE THREAD

**Issue by DuyThangDecima** [grpc-ecosystem/grpc-gateway#685]
My project written Java, I don't find document install, use ... for Java
Help me.

**Comment by achew22** [comment]
@DuyThangDecima did you try reading through the documentation? Do you have a gRPC server running in Java already? What have you tried doing?

**Comment by alvoron** [comment]
Let me proceed this thread, since I have the same task. I have a Spring Boot application. I was able to run gRPC server in it, it works fine. 
Then I decided to add REST interface. I have genereted reverse-proxies. Example entrypoint is written using Go and I haven't seen how can I use built in Tomcat from Spring Boot to host reverse-proxies. Can grpc-gateway generate Java proxies? Or there is another way to use Spring Boot Tomcat instead of Go web server?

**Comment by achew22** [comment]
As of right now, grpc-gateway doesn't generate any Java code, let alone spring boot definitions. There's no way to generate a version of grpc-gateway that runs in Tomcat instead of in the go run time. There are, however, some projects that generate similar functionality for Java. I've never used them and cannot attest to their quality but I do know they exist. I'm reluctant to recommend any particular one though because I haven't used any of them. They're pretty easy to find on Google. Do you have any luck with them, please report back here so we can find out what the experience is like.

Thank you!

**Comment by CosminaMusat** [comment]
Is this issue still existing? 
I still can't use grpc-gateway for a pure Java project with Spring Boot? 
My application (server-side) needs to be written in Java and we have to expose APi's both with gRPC and REST.
From what I understood so far is impossible to do this in a Spring Boot app?
Regards!

**Comment by achew22** [comment]
Please see earlier comments for how you might be able to achieve a similar result in Java. If you have specific concerns with this repo, please open a new issue and let's talk about them there.
