### ISSUE TITLE
Support specifying servers in the swagger generator

### ISSUE THREAD

**Issue by PassKit** [grpc-ecosystem/grpc-gateway#891]
Currently it is not possible to specify servers in `grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger`.

This necessitates a manual edit of the JSON before it can be published as documentation.

**Comment by johanbrandhorst** [comment]
Hi, thanks for raising this issue. How can I help you contribute a fix for this?

**Comment by bentranter** [comment]
Hey @johanbrandhorst, it looks like the reporter of this issue was expecting the OpenAPI v3 definitions (seen [in the latest Swagger spec](https://swagger.io/docs/specification/api-host-and-base-path/)) which contains a `servers` array, whereas gRPC Gateway only supports Swagger v2, which [doesn't contain a servers array](https://swagger.io/docs/specification/2-0/api-host-and-base-path/), but rather only allows users to define `host`, `basePath`, and `schemes` fields. I think this issue can be closed.

**Comment by johanbrandhorst** [comment]
Great spot @bentranter, thanks!
