### ISSUE TITLE
Marshalling of response object is bad for int64 properties

### ISSUE THREAD

**Issue by donutloop** [grpc-ecosystem/grpc-gateway#920]
### What version of protobuf and what language are you using?
Version: libprotoc 3.7.0
Language: GOLANG
Version v1.3.1

### What version of Go are you using (`go version`)?

go version go1.12 darwin/amd64

### What operating system (Linux, Windows, …) and version?

MacOS Mojave 10.14.1 (18B75)

### What did you do?

i had defined a message in Protobuffer this message contains a property called  "property name: status, type:int64". if i send a response to the requester then i get instead of "int" a "string" as type back.

Input:

```go
message HealthCheckResponse {
   repeated HealthStatus statusList = 1;
}

message HealthStatus {
    int64 status = 1;
    string service = 3;
}
```

### What did you expect to see?

Output:

```bash
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: application/json
Date: Fri, 05 Apr 2019 16:03:38 GMT
Grpc-Metadata-Content-Type: application/grpc

{"statusList":[{"status":1,"service":"Database"}]}
```
### What did you see instead?

Output:

```bash
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: application/json
Date: Fri, 05 Apr 2019 16:03:38 GMT
Grpc-Metadata-Content-Type: application/grpc

{"statusList":[{"status":"1","service":"Database"}]}
```

**Comment by achew22** [comment]
Hey @donutloop, thanks for sending in the issue. This has been discussed quite extensively in https://github.com/grpc-ecosystem/grpc-gateway/issues/219#issuecomment-251250029, #438, #735 and a few more. It's unlikely to change because there is a correctness issue, and we have no ability to change without dramatically changing the way JSON is handled in the core of protobuf (which would require an ecosystem wide migration).

Do you have any ideas on how could we make this behavior more obviously correct? Did you look in our documentation before filing an issue? If so, where so I can add more links and words. Thanks so much!

**Comment by donutloop** [comment]
Have you opened a ticket on this protobuffer repository to discuss this issue in detail?  It's definitely a major bug and it should be get fixed by this protobuffer team

**Comment by achew22** [comment]
@donutloop, thanks for the response. Based on [this comment](https://github.com/grpc-ecosystem/grpc-gateway/issues/219#issuecomment-251250029), do you really think it is a bug to handle things this way?

```
> (Math.pow(2,53) + 0) == (Math.pow(2,53) + 1)
true
```

is a sentiment that really scares me as an API designer and I'm generally in agreement with the protobuf team that this is the correct design even if it is unintuitive. Could you elaborate a bit on why you think it is a "major bug"?

**Comment by mgtest42** [comment]
I faced this behavior on the step of testing my rest service.
Can I access grpc-gateway internal JSON serializer?
Because of this, I can't properly compare the expected response with actual.
Golang JSON library marshals int64 as floats, and I can't force it to marshal it to strings.
And on the other hand, grpc-gateway returns a string, which can't be unmarshalled into original structs by the standard library.

**Comment by johanbrandhorst** [comment]
You can specify your own Marshaller with the runtime.WithMarshaler option.
