### ISSUE TITLE
protoc-gen-grpc-gateway: Add support for upstream protos.

### ISSUE THREAD

**Issue by jeremyje** [grpc-ecosystem/grpc-gateway#966]
I want to create a service based on `operations.proto` in the googleapis package. This is challenging because the `operations.pb.go` is already available so if I generate a reverse proxy go file, `operations.pb.gw.go` it'll assume that `operations.pb.go` is in the same package where it won't be because I don't own the upstream `google.golang.org/genproto/googleapis/longrunning` package. 

**Basically am I asking for the `.pb.gw.go` file to live in a different package from the `.pb.go` file.**

**Comment by johanbrandhorst** [comment]
Interesting idea, obviously the existing generator assumes it will have access to the internals of the package by virtue of being generated into the same folder. What is currently breaking if you just output it to a different folder and add an import? I would expect things like oneofs might not be possible.

It might be something we could support with a generator flag. Would you be interested in contributing a fix for this?

**Comment by ivucica** [comment]
I'd say this is not a huge problem. I agree with @johanbrandhorst, why can't you regenerate the `google.golang.org/genproto/googleapis/longrunning`? Ideally it should not be a problem just because you're regenerating `operations.pb.go` and getting no diff from upstream. And it should not be hard if you are building everything from source instead of using prebuild packages in `$GOPATH/pkg` (does that even work? I never tried).

You can also use the `-M` flag passed to `protoc-gen-go` to specify a different package, but that might cause different problems (conflict between two Go packages registering the same type), but that's the tradeoff.
